FROM ubuntu:latest
# Install Node.js and npm
RUN apt-get install -y npm
# Bundle app source
COPY ./*
# Install app dependencies
RUN npm install
# Install mocha and bower and coffee and less and nodemon
RUN npm install -g bower mocha less coffee-script nodemon
# Expose the port
EXPOSE  8080
# Run
CMD mocha
