FROM ubuntu:latest
# Install curl
RUN apt-get install -y curl
# Install Node.js and npm
RUN curl --silent --location https://deb.nodesource.com/setup_0.12 | sudo bash -
RUN apt-get install -y nodejs
# Get source

# Install app dependencies
RUN npm install
# Install mocha and bower and coffee and less and nodemon
RUN npm install -g bower mocha less coffee-script nodemon
# Expose the port
EXPOSE  8080
# Run
CMD mocha
