// Generated by CoffeeScript 1.9.3
(function() {
    var clicolour, fs, instances, path;

    instances = require('./instances/index.js');

    fs = require('fs');

    path = require('path');

    clicolour = require('cli-color');

    exports.checkInstances = function(x) {
        return fs.stat('instances', function(err, stat) {
            if (err === null) {
                return console.log('File exists');
            } else if (err.code === 'ENOENT') {
                return instances.instancescreateInstancesDir("ok");
            } else {
                return clicolour.yellowBright("Jakhu ran into a problem,", "To protect your data, we have shut down Jakhu", "                             ", "This error code may help:", "SETUP_DIR_INSTANCES_OTHER_" + err.code, "              ", "Here's the full error:", +err.code + err);
            }
        });
    };

}).call(this);