// Generated by CoffeeScript 1.9.3
(function() {
    var clicolour, mkdirp;

    mkdirp = require('mkdirp');

    clicolour = require('cli-color');

    exports.createInstancesDir = function(x) {
        return mkdirp('instances', function(err) {
            if (err) {
                return errors.bsod.throwError("SETUP_CREATE_DIR_INSTANCES", err, err.code);
            } else {
                return console.log(clicolour.cyanBright("Jakhu ") + clicolour.yellowBright("setup ") + "Create Instances Dir");
            }
        });
    };

}).call(this);