// Generated by CoffeeScript 1.9.3
(function() {
    var lang, message;

    exports.set - (lang = require(setLang.coffee));

    exports.set - error - (message = require(setLang.coffee));

}).call(this);