#!/usr/env/node
var exec = require('child_process').exec;
var os = require('os');

// This is the Web-OS install script

// Get arguments
var args = process.argv.slice(2);
console.log(process.argv.slice(2));

if(args === "[ 'h' ]"){
  console.log("ok");
}
