#!/usr/env/node
var exec = require('child_process').exec;
var os = require('os');
var commander = require('commander');

// This is the Web-OS install script

console.log("Web-OS install script");
console.log("                     ");
console.log("May exit with an nodejs error if no os is defined");
console.log("                     ");

// Get arguments
commander
  .version('0.0.1')
  .option('-l, --local', 'Installs all the apps in /packages/ using msiexec and adds it to the path for the server on startup (Only avalible on Windows and Linux)')
  .arguments('<os>')
  .action(function (os) {
    if(os === undefined){
      console.log("Please specify the OS you are running. Valid arguments are 'Linux' 'Windows_NT' (That's normal Windows) and 'OSX'");
      //process.exit(1);
    }
    console.log("Running: "+os);
    osl = os;
  })
  .parse(process.argv);

if(typeof osl === undefined){
  console.log("Please specify the OS you are running. Valid arguments are 'Linux' 'Windows_NT' (That's normal Windows) and 'OSX'");
  console.log("Exiting with exit code 1");
  process.exit(1);
} else {
  if(osl !== 'Linux' && osl !== 'Windows_NT' && osl !== 'OSX'){
    console.log("Please specify a valid OS. Valid arguments are 'Linux' 'Windows_NT' (That's normal Windows) and 'OSX'");
    console.log("Exiting with exit code 1");
    process.exit(1);
  }
}
